[package]
name = "logga"
version = "0.1.0"
edition = "2024"
default-run = "loggabin"

[lib]
name = "loggalib"
path = "src/lib/lib.rs"

[[bin]]
name = "loggabin"
path = "src/bin/main.rs"

[[bin]]
name = "loggademo"
path = "demo/main.rs"

[dependencies]
anyhow = "1.0.100"
bytes = "1.11.0"
futures = "0.3.31"
itertools = "0.14.0"

quinn = {
    version = "0.11.11",
    default-features = false,
    features = ["runtime-tokio", "rustls-aws-lc-rs"]
}

rcgen = {
    version = "0.14.7",
    default-features = false,
    features = ["aws_lc_rs", "x509-parser"]
}

rustls = {
    version = "0.23",
    default-features = false,
    features = ["std", "aws_lc_rs"]
}

tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"

[dependencies.uuid]
version = "1.18.1"
# Lets you generate random UUIDs
features = [
    "v4",
]

[dev-dependencies]
x509-parser = "0.18.0"

[workspace.lints.clippy]
pedantic = "warn"
